### ISSUE TITLE
Fill in port 443 when receiving a https Address

### ISSUE THREAD

**Issue by HarHarLinks** [imLinguin/jelly-desktop#1]
The announcement info includes no port, at least in my case.
It probably makes sense to assume 443 when it's a https address? Maybe even 80 when plain http?

If you think that assuming the jelly default port still makes more sense, then perhaps try these ports if the jelly default port doesn't work.

**Comment by imLinguin** [comment]
In terms of https that sounds like good idea, we could also do some kind of check on certain ports to even auto detect it. This can be done by making a request to Jellyfin specific endpoint.
