### ISSUE TITLE
Crash when impatiently clicking connect again while already making a connection

### ISSUE THREAD

**Issue by HarHarLinks** [imLinguin/jelly-desktop#2]
I had entered some incorrect ports so jelly was stuck for a while until eventually `ERR_CONNECTION_TIMED_OUT`.

If, since there is no loading indicator, you click again before the connection times out, the app crashes.

**Comment by imLinguin** [comment]
I did some investigation, I found the problem and fixed it. It's currently on devel branch. Will be available on next release.
